Try tests

diff --git a/.github/workflows/rocm-ci.yml b/.github/workflows/rocm-ci.yml
--- a/.github/workflows/rocm-ci.yml
+++ b/.github/workflows/rocm-ci.yml
@@ -108,23 +108,23 @@ jobs:
             pip install dist/apex-*.whl
           "
 
-      - name: Run L0 tests
-        if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_l0 }}
-        run: |
-          docker exec apex-test-container bash -c "
-            set -eo pipefail
-            cd tests/L0
-            sh run_rocm.sh 2>&1 | tee ../../L0_results.log
-          "
+      # - name: Run L0 tests
+      #   if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_l0 }}
+      #   run: |
+      #     docker exec apex-test-container bash -c "
+      #       set -eo pipefail
+      #       cd tests/L0
+      #       sh run_rocm.sh 2>&1 | tee ../../L0_results.log
+      #     "
 
-      - name: Run Contrib tests
-        if: ${{ (success() || failure()) && (github.event_name != 'workflow_dispatch' || inputs.run_contrib) }}
-        run: |
-          docker exec apex-test-container bash -c "
-            set -eo pipefail
-            cd apex/contrib/test
-            python3 run_rocm_extensions.py 2>&1 | tee ../../../contrib_results.log
-          "
+      # - name: Run Contrib tests
+      #   if: ${{ (success() || failure()) && (github.event_name != 'workflow_dispatch' || inputs.run_contrib) }}
+      #   run: |
+      #     docker exec apex-test-container bash -c "
+      #       set -eo pipefail
+      #       cd apex/contrib/test
+      #       python3 run_rocm_extensions.py 2>&1 | tee ../../../contrib_results.log
+      #     "
 
       - name: Run Peer Halo Exchange tests
         if: ${{ (success() || failure()) && (github.event_name != 'workflow_dispatch' || inputs.run_halo) }}
@@ -132,7 +132,6 @@ jobs:
           docker exec apex-test-container bash -c "
             set -eo pipefail
             torchrun --nproc_per_node 8 \
-              --bind_all \
               apex/contrib/peer_memory/peer_halo_exchange_module_tests.py 2>&1 | tee halo_results.log
           "
 
